### ISSUE TITLE
legendary is my daddy 

### ISSUE THREAD

**Issue by p-asha** [leg1337/hahahaahha#1]
hi my name is Pasha i’m 13 years old and i love to script. i also meat ride everyone who is cooler than me. i hope you come back to roblox it would be very cool bye bye

**Comment by v9h** [comment]
TRUTH

**Comment by leg1337** [comment]
Hey guys, thank you for the responses. I’d love to come back to Roblox however things have changed and it’s better if I stay away from Roblox for now. You guys can still suck each other off just I won’t be there ;) 

Regards,
Legendary.
